### ISSUE TITLE
i don't know

### ISSUE THREAD

**Issue by Tamago4a** [kingsplayground/Ultimate-AFK#1]
![unknown](https://user-images.githubusercontent.com/47304666/89129007-45727000-d502-11ea-8901-f5876cf4356e.png)
wtf

**Comment by Tamago4a** [comment]
i use 2.0.7 exiled

**Comment by Tamago4a** [comment]
It looks like your plugin conflicts with the one my coder made for me. But the error is yours, not my plugin.

**Comment by MrCreaper** [comment]
idk man seems like a u problem

**Comment by Tamago4a** [comment]
> idk man seems like a u problem

One plugin of mine conflicts with this plugin. And I will repeat it again. My coder says that the error is in the UAFK plugin.

**Comment by MrCreaper** [comment]
well you coder is wrong :)

**Comment by thomasjosif** [comment]
This is nothing to do with my plugin. You either have a misconfigured permissions config file or some other plugin is screwing with the permissions causing the errors that you see. 

Sorry for the late reply, but it is what it is.
