### ISSUE TITLE
i dont know #2

### ISSUE THREAD

**Issue by Tamago4a** [kingsplayground/Ultimate-AFK#3]
settings default
![Снимок](https://user-images.githubusercontent.com/47304666/94993333-ef20bc80-0598-11eb-8422-b64721d9c180.PNG)

**Comment by thomasjosif** [comment]
Without knowing the correlation between the errors and who was replaced and if they were the one that disconnected I can't help you. I also would need valid steps to replicate these errors. 

If you have both feel free to open a new issue.
