### ISSUE TITLE
Suggestion - Rank Check

### ISSUE THREAD

**Issue by ripjaw567** [kingsplayground/Ultimate-AFK#8]
A way to maybe add a rank or user steamIDs to a list that prevents UAfk from replacing/kicking them (Ex: Staff AFKing to go check for new reports, UAFK would overlook them because they are staff)

**Comment by thomasjosif** [comment]
Sorry for the delay in replying, if you look at the readme you can see that all you have to do is assign the uafk.ignore permission.
